name: push

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_LOGIN }}
  BACKEND_IMAGE_NAME: annotation-api
  FRONTEND_IMAGE_NAME: annotation-app

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build backend image
        run: |
          docker build \
            -f annotation_api/Dockerfile \
            annotation_api \
            -t $DOCKERHUB_USER/$BACKEND_IMAGE_NAME:latest

      - name: Build frontend image
        run: |
          docker build \
            -f frontend/Dockerfile \
            frontend \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
            --build-arg VITE_ENVIRONMENT=production \
            -t $DOCKERHUB_USER/$FRONTEND_IMAGE_NAME:latest

      - name: Push images to DockerHub
        run: |
          docker push $DOCKERHUB_USER/$BACKEND_IMAGE_NAME:latest
          docker push $DOCKERHUB_USER/$FRONTEND_IMAGE_NAME:latest
