name: push

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_LOGIN }}
  BACKEND_IMAGE_NAME: annotation-api
  FRONTEND_IMAGE_NAME: annotation-app
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.8.3"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend dependencies with Poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64

      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Resolve backend dependencies
        working-directory: annotation_api
        run: poetry export -f requirements.txt --without-hashes --output requirements.txt

      # Build backend image from ./annotation_api
      - name: Build backend image
        run: |
          docker build \
            -f annotation_api/Dockerfile \
            annotation_api \
            -t $DOCKERHUB_USER/$BACKEND_IMAGE_NAME:latest

      # Build frontend image from ./frontend
      - name: Build frontend image
        run: |
          docker build \
            -f frontend/Dockerfile \
            frontend \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
            --build-arg VITE_ENVIRONMENT=production \
            -t $DOCKERHUB_USER/$FRONTEND_IMAGE_NAME:latest

      # Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PW }}

      # Push images to Docker Hub
      - name: Push images to DockerHub
        run: |
          docker push $DOCKERHUB_USER/$BACKEND_IMAGE_NAME:latest
          docker push $DOCKERHUB_USER/$FRONTEND_IMAGE_NAME:latest
